//
//  GameAction.swift
//  Imposter
//
//  All possible actions that can modify game state.
//

import Foundation
import UIKit

// MARK: - GameAction

/// All possible actions that can be dispatched to modify game state.
/// Actions are processed by the GameReducer to produce new state.
enum GameAction: Sendable {

    // MARK: - Setup Phase

    /// Add a new player to the game
    case addPlayer(name: String, color: PlayerColor)

    /// Update the secret word (used when generating word from AI)
    case setGeneratedWord(word: String)

    /// Update the imposter hint (generated by AI)
    case setImposterHint(hint: String)

    /// Remove a player from the game
    case removePlayer(id: UUID)

    /// Update an existing player's name and/or color
    case updatePlayer(id: UUID, name: String, color: PlayerColor)

    /// Update game settings
    case updateSettings(GameSettings)

    /// Start the game (transitions from setup to roleReveal)
    case startGame

    // MARK: - Role Reveal Phase

    /// Mark that a player has viewed their role
    case revealRoleToPlayer(id: UUID)

    /// All players have seen their role, proceed to clue round
    case completeRoleReveal

    // MARK: - Clue Round Phase

    /// Submit a clue from the current player
    case submitClue(playerID: UUID, text: String)

    /// Move to the next player's clue turn
    case advanceToNextClue

    /// All required clues have been given
    case completeClueRounds

    // MARK: - Discussion & Voting Phase

    /// Start the discussion phase
    case startDiscussion

    /// End discussion early (or when timer expires)
    case endDiscussion

    /// Start the voting phase
    case startVoting

    /// Record a vote from a player
    case castVote(voterID: UUID, suspectID: UUID)

    /// All votes have been cast
    case completeVoting

    // MARK: - Reveal Phase

    /// Trigger the reveal of the imposter's identity
    case revealImposter

    /// Imposter attempts to guess the secret word
    case imposterGuessWord(guess: String)

    /// Conclude the round and calculate scores
    case completeRound(imposterGuessedCorrectly: Bool)

    // MARK: - Summary/Reset

    /// Start a new round with the same players
    case startNewRound

    /// End the entire game
    case endGame

    /// Return to the home screen (resets state)
    case returnToHome

    /// Reset the entire game state
    case resetGame

    // MARK: - Error Handling

    /// Word generation failed
    case wordGenerationFailed(GameActionError)

    /// Image generation failed
    case imageGenerationFailed(GameActionError)

    /// Storage operation failed
    case storageFailed(GameActionError)

    /// Set the generated image for the current round
    case setGeneratedImage(UIImage)
}

// MARK: - GameActionError

/// Sendable-compatible error wrapper for actions
struct GameActionError: Sendable, LocalizedError {
    let message: String
    let underlyingDescription: String?

    init(_ error: Error) {
        self.message = error.localizedDescription
        self.underlyingDescription = String(describing: error)
    }

    init(message: String) {
        self.message = message
        self.underlyingDescription = nil
    }

    var errorDescription: String? {
        message
    }
}

// MARK: - Action Descriptions

extension GameAction: CustomStringConvertible {
    var description: String {
        switch self {
        case .addPlayer(let name, _):
            return "Add player: \(name)"
        case .setGeneratedWord(let word):
            return "Set generated word: \(word)"
        case .setImposterHint(let hint):
            return "Set imposter hint: \(hint)"
        case .removePlayer(let id):
            return "Remove player: \(id)"
        case .updatePlayer(let id, let name, _):
            return "Update player \(id): \(name)"
        case .updateSettings:
            return "Update settings"
        case .startGame:
            return "Start game"
        case .revealRoleToPlayer(let id):
            return "Reveal role to player: \(id)"
        case .completeRoleReveal:
            return "Complete role reveal"
        case .submitClue(let playerID, let text):
            return "Submit clue from \(playerID): \(text)"
        case .advanceToNextClue:
            return "Advance to next clue"
        case .completeClueRounds:
            return "Complete clue rounds"
        case .startDiscussion:
            return "Start discussion"
        case .endDiscussion:
            return "End discussion"
        case .startVoting:
            return "Start voting"
        case .castVote(let voterID, let suspectID):
            return "Vote: \(voterID) suspects \(suspectID)"
        case .completeVoting:
            return "Complete voting"
        case .revealImposter:
            return "Reveal imposter"
        case .imposterGuessWord(let guess):
            return "Imposter guesses: \(guess)"
        case .completeRound(let correct):
            return "Complete round (imposter guessed: \(correct))"
        case .startNewRound:
            return "Start new round"
        case .endGame:
            return "End game"
        case .returnToHome:
            return "Return to home"
        case .resetGame:
            return "Reset game"
        case .wordGenerationFailed(let error):
            return "Word generation failed: \(error.message)"
        case .imageGenerationFailed(let error):
            return "Image generation failed: \(error.message)"
        case .storageFailed(let error):
            return "Storage failed: \(error.message)"
        case .setGeneratedImage:
            return "Set generated image"
        }
    }
}
